#+title: QuakEmacs
#+description: A doom emacs config for a confused ID fan.
#+PROPERTY: header-args :eval no-export :exports code :results none

* Helper functions
** Regex string functions
*** capture group
#+begin_src emacs-lisp
(defun string-match-group (regexp string &optional group)
  "Return the data matched by capture `group' of `regexp' in `string'."
  (save-match-data (string-match regexp string)
                   (match-string (or group 0) string)))
#+end_src
* Emacs
** Emacs server
Emacs is damn slow! I got more ram than I do patience, so run it in the background
#+begin_src emacs-lisp
(server-start)
(setq org-directory "~/Documents/Notes/")
#+end_src
* Vim
I prefer to use vim, so I like to have as much feature parity with vim as possible so I
don't get confused.
** Relative line numbers
Emacs for some reason has folded lines included by default if you don't use ='visual=.
#+begin_src emacs-lisp
(setq display-line-numbers-type 'visual)
#+end_src

* Visuals
I may have bad vision, but that doesn't mean I don't appreciate some fancy visual flares.

#+begin_src emacs-lisp
(setq display-line-numbers-type 'visual
      fill-column 90
      global-display-fill-column-indicator-mode t)
#+end_src

** Auto save
*** Real auto save
#+begin_src emacs-lisp
(use-package! real-auto-save
  :after org
  :ensure t
  :custom
  (real-auto-save-interval 5)
  (real-auto-save-silent t)
  :hook
  (org-mode . real-auto-save-mode)
  (markdown-mode . real-auto-save-mode)
  (text-mode . real-auto-save-mode))
#+end_src
* Org
#+begin_src emacs-lisp
(use-package! org
  :ensure org-plus-contrib
  )
#+end_src
** Packages
*** ox-typst
I want to be able to write and publish things like slidedeck, whitepapers, and
blog posts all from orgmode. Typst will let me render PDFs and HTML for both
whitepapers and slidedeck respectively.
#+begin_src emacs-lisp
(use-package! ox-typst
  :after ox
  :config
  (require 'ox-typst))
#+end_src
*** org-pomodoro
I like time tracking
#+begin_src emacs-lisp
(use-package! org-pomodoro
  :after org)
#+end_src
*** org-protocol
#+begin_src emacs-lisp
(use-package! org-protocol
  :after org)
#+end_src
*** org-id
**** Setup org-id
rest of the settings
#+begin_src emacs-lisp
(use-package! org-id
  :after org
  :hook (after-save . org-id--update-id-after-save-hook)
  :custom
  (org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
  (org-id-method 'org)
  (org-id-include-domain t)
  (org-id-locations-file (expand-file-name ".org-id-locations" doom-cache-dir)))

#+end_src
**** Auto update id locations
A quick and dirty function to automatically update ids using =org-id-update-id-locations=
for only the buffer that was saved.

This probably will be slow so we'll run it only if the buffer:
- Has an associated file name
  - It will also bind this to avoid it suddenly changing
- Is an org-mode buffer
- Has an ID in the first place
  - We use the =id-regexp= found in [[file:~/.config/emacs/.local/straight/repos/org/lisp/org-id.el::id-regexp][org-id.el]]
    #+transclude: [[file:~/.config/emacs/.local/straight/repos/org/lisp/org-id.el::id-regexp][id-regexp in org-id.el]] :lines -3 :src emacs-lisp
- Is not a remote file

#+begin_src emacs-lisp
(defun org-id--update-id-after-save-hook ()
  (if-let* ((name (buffer-file-name)))
      (when (and (derived-mode-p 'org-mode)
                 (save-excursion
                   (goto-char (point-min))
                   ;; 'id-regexp' in org-id.el
                   (re-search-forward
                    (rx (seq bol (0+ (any "\t ")) ":ID:" (1+ " ") (not (any " "))))
                    nil t))
                 (not (file-remote-p name)))
        (org-id-update-id-locations '(name) t))))
#+end_src

*** org-web-tools
**** URL Property
What org-mode property will we be using to archive and attach. Defaults to =URL=

#+begin_src emacs-lisp
(defcustom org-web-tools-archive-property-name "URL"
  "The `org-mode' property to apply to `org-web-tools-archive-attach'."
  :group 'org-web-tools-archive
  :type 'string)

#+end_src

**** Archive and attach an orgmode entry
:PROPERTIES:
:ID:       kf060p00fnk0@archlinux.mail-host-address-is-not-set
:END:
This function is intended to be run from [[help:org-map-entries][org-map-entries]]
#+begin_src emacs-lisp
(defun org-web-tools-archive-attach--entry ()
  ;; Use if-let to return early for performance
  (if-let* ((url (org-entry-get org-web-tools-archive-property-name)))
      (org-web-tools-archive-attach url)))
#+end_src
**** Setup the package
Now to set up org-web-tools with what we have
#+begin_src emacs-lisp
(use-package! org-web-tools
  :after org
  ;; Hook each capture so that we can archive and attach the URL for each org entry
  :config
  (add-hook!
   'org-capture-prepare-finalize-hook
   (org-map-entries (org-web-tools-archive-attach
                     (org-entry-properties (point)
                                           org-web-tools-archive-property-name)))))
#+end_src
*** org-transclusion
#+begin_src emacs-lisp
(use-package! org-transclusion
 :after org
 :init
 (map!
  :leader
  :prefix "n"
  :desc "Org Transclusion Mode" "t" #'org-transclusion-mode))
#+end_src
** Org archive
*** Complete tasks on archive
Automatically close tasks so I don't have unfinished tasks in my archive.
#+begin_src emacs-lisp
(after! org
  (setq org-archive-mark-done t))
#+end_src

** Source code blocks
*** Autosave src blocks
I like using =org-edit-special= but hate accidentally closing it before saving.
**** Idle delay
Set =org-edit-src-auto-save-idle-delay= to automatically save after N seconds.
#+begin_src emacs-lisp
(after! org
  (let ((auto-save-delay 5))
    (setq org-edit-src-auto-save-idle-delay auto-save-delay
          org-edit-src-turn-on-auto-save (not auto-save-delay))))
#+end_src
**** Turn on auto-save
=org-edit-src-auto-save-idle-delay= and =org-edit-src-turn-on-auto-save= are mutually
exclusive so we'll ensure that if the delay is set, autosave is set to =nil=
#+begin_src emacs-lisp
(after! org (setq org-edit-src-turn-on-auto-save
                  (> org-edit-src-auto-save-idle-delay 0)))
#+end_src
** Files and directories
#+begin_src emacs-lisp
(after! org
  (setq! org-archive-location "~/Documents/Notes/Archive/%s_archive::"
         org-default-notes-file (concat org-directory
                                        "/inbox.org")
         org-agenda-files (directory-files-recursively org-directory
                                                       "^[A-Za-z\/~_-]*\.org$")
         org-todo-keywords '((sequence
                              "TODO(t)" "NEXT(n)" "PROJ(p)" "LOOP(r)"
                              "STRT(s)" "WAIT(w)" "HOLD(h)" "IDEA(i)" "|"
                              "DONE(d)" "KILL(k)"))
         org-download-screenshot-method "/usr/bin/grimshot save anything \"%s\""))
#+end_src
** Structure templates
I like to write code snippets a lot
*** Emacs Lisp
For this literate config 😻
#+begin_src emacs-lisp
(after! org
  (add-to-list
   'org-structure-template-alist
   '("L" . "src emacs-lisp")))
#+end_src


*** Bash
I write a lot of shell scripts with literate devops!
#+begin_src emacs-lisp
(add-to-list
   'org-structure-template-alist
   '("b" . "src bash"))
#+end_src

** capture templates
#+begin_src emacs-lisp
(after! org
  (setq org-capture-templates
        '(("M" "Meeting minutes" entry
           (file+olp+datetree "~/Documents/Notes/work.org" "Minutes")
           "* NEXT %? - %U\n** Notes\n** Action items" :clock-in t :clock-resume t)
          ("p" "Phone call" entry
           (file+headline "~/Documents/Notes/inbox.org" "Phone")
           "* PHONE %?  :PHONE:\n%U" :clock-in t :clock-resume t)
          ("i" "Interruption" entry
           (file+olp+datetree "~/Documents/Notes/journal.org" "Interruptions")
           "* %?  \n%U" :clock-in t :clock-resume t)
          ("t" "Task to be refiled later" entry
           (file+headline "~/Documents/Notes/inbox.org" "Tasks")
           "* TODO %?
 %a" :clock-in t :clock-resume t)
          ("I" "Ideas" entry
           (file "~/Documents/Notes/Personal/ideas.org")
           "* %?
 %i")
          ("s" "Snippets" entry
           (file+headline "~/Documents/Notes/inbox.org" "Snippets")
           "* %^{Title}
Source: %u, %c
 ,#+BEGIN_QUOTE
%i
,#+END_QUOTE
[[%:link][%:description]]
%?")
          ("q" "Quotes" entry
           (file+headline "~/Documents/Notes/inbox.org" "Quotes")
           "* %?
:PROPERTIES:
:URL: %:link
:END:

Source: %u, [[%:link][%:description]]
,#+BEGIN_QUOTE
%i
,#+END_QUOTE")
          ("b" "Bookmarks" entry
           (file+headline "~/Documents/Notes/inbox.org" "Bookmarks")
           "* %?[[%:link][%:description]]
:PROPERTIES:
:URL: %:link
:END:
Captured On: %U" :immediate-finish t)
          ("j" "Journal Entries" entry
           (file+olp+datetree "~/Documents/Notes/journal.org" "Personal")
           "* %U - %^{Title}
%i
%?")
          ("J" "Journal Entries" entry
           (file+olp+datetree "~/Documents/Notes/journal.org" "Work")
           "* %U - %^{Title}
%i
%?")
          ("T" "TIL" entry
           (file+olp+datetree "~/Documents/Notes/journal.org" "TIL")
           "* %U - Today I learnt: %^{Title}
%i
Today I learned that %^{Title} %?")))
  )
#+end_src

** Custom [[https://orgmode.org/manual/Hyperlinks.html][hyperlinks]]
*** man
I like being able to quickly link to [[man:man(1)][man(1)]] pages, so let's set them up.
**** Helper functions
The bulk of the logic is defined in these functions, which are sourced directly
from [[https://orgmode.org/manual/Adding-Hyperlink-Types.html][Adding Hyperlink Types]] in the [[https://orgmode.org/manual/index.html][orgmode online manual]].
#+begin_src emacs-lisp
(defcustom org-man-command 'man
    "The Emacs command to be used to display a man page."
    :group 'org-link
    :type '(choice (const man) (const woman)))

  (defun org-man-open (path _)
    "Visit the manpage on PATH.
PATH should be a topic that can be thrown at the man command."
    (funcall org-man-command path))

  (defun org-man-store-link (&optional _interactive?)
    "Store a link to a man page."
    (when (memq major-mode '(Man-mode woman-mode))
      ;; This is a man page, we do make this link.
      (let* ((page (org-man-get-page-name))
             (link (concat "man:" page))
             (description (format "Man page for %s" page)))
        (org-link-store-props
         :type "man"
         :link link
         :description description))))

  (defun org-man-get-page-name ()
    "Extract the page name from the buffer name."
    ;; This works for both `Man-mode' and `woman-mode'.
    (if (string-match " \\(\\S-+\\)\\*" (buffer-name))
        (match-string 1 (buffer-name))
      (error "Cannot create link to this man page")))

  (defun org-man-export (link description format)
    "Export a man page link from Org files."
    (let* ((regexp "\\(\\w+\\)(\\([0-9]+\\))")
           (topic (string-match-group regexp link 1))
           (section (string-match-group regexp link 2))
           (path (format "https://linux.die.net/man/%s/%s" topic section))
           (desc (or description link)))
      (pcase format
        (`html (format "<a target=\"_blank\" href=\"%s\">%s</a>" path desc))
        (`md (format "[%s](%s)" desc path))
        (`latex (format "\\href{%s}{%s}" path desc))
        (`texinfo (format "@uref{%s,%s}" path desc))
        (`ascii (format "%s (%s)" desc path))
        (t path))))
#+end_src
**** Add the link type
:PROPERTIES:
:ID:       y43kk3204ok0@archlinux.mail-host-address-is-not-set
:END:
Once we have the code to support linking to man pages, we should add it via the
[[help:org-link-set-parameters][org-link-set-parameters]] orgmode function.
#+begin_src emacs-lisp
(after! ol
  (org-link-set-parameters
   "man"
   :follow #'org-man-open
   :export #'org-man-export
   :store #'org-man-store-link))
#+end_src
* Org roam
#+begin_src emacs-lisp
(use-package! org-roam
  :custom
  (org-roam-completion-everywhere t)
  (org-roam-capture-ref-templates
   '(("w" "ref" plain "%(replace- org-web-tools--url-as-readable-org \"${ref}\")"
      :target (file+head "${slug}.org" "#+title: ${title}\n")
      :unnarrowed t)))
  (org-roam-directory (file-name-concat org-directory "Wiki"))
  (org-roam-dailies-directory "../Journal")
  :config
  (require 'org-roam-dailies)
  (org-roam-db-autosync-mode)
  ;; TODO optimize/cache this and also clean up code
  (progn
    (defun org-roam--refile-targets ()
      (append (directory-files org-roam-dailies-directory t "^[0-9]+-[0-9\-]+\.org$")
              (directory-files org-roam-directory t "^[0-9]+-[[:alpha:]]+\.org$")))
    (add-to-list 'org-refile-targets
                 '(org-roam--refile-targets :maxlevel . 2))))
(use-package! org-roam-protocol)
(use-package! websocket
  :ensure t)

(use-package! org-roam-ui
  :after org-roam ;; or :after org
  ;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
  ;;         a hookable mode anymore, you're advised to pick something yourself
  ;;         if you don't care about startup time, use
  ;;  :hook (after-init . org-roam-ui-mode)
  :custom
  (org-roam-ui-sync-theme t)
  (org-roam-ui-follow t)
  (org-roam-ui-update-on-save t)
  (org-roam-ui-open-on-start t))
#+end_src
* Coding
** LSPs
*** Copilot
#+begin_src emacs-lisp
;;; (use-package! copilot
;;;   :hook (prog-mode . copilot-mode)
;;;   :bind ("C-TAB" . #'copilot-accept-completion)
;;;   :config
;;;   (add-to-list 'copilot-indentation-alist '(prog-mode 2))
;;;   (add-to-list 'copilot-indentation-alist '(org-mode 2))
;;;   (add-to-list 'copilot-indentation-alist '(text-mode 2))
;;;   (add-to-list 'copilot-indentation-alist '(closure-mode 2))
;;;   (add-to-list 'copilot-indentation-alist '(emacs-lisp-mode 2)))
#+end_src
